global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).
scrape_configs:
  - job_name: 'hyperledger_fabric'
    static_configs:
      - targets: 
        - 'peer0.org1.example.com:9100'
        - 'peer1.org1.example.com:9100'
        - 'peer0.org2.example.com:9100'
        - 'peer1.org2.example.com:9100'
        - 'orderer.example.com:9100'